version: "3.9"

services:
  mysqldb:
    image: mysql:8.0
    env_file: ./.env.docker
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQLDB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQLDB_DATABASE}
    ports:
      - "${MYSQLDB_LOCAL_PORT}:${MYSQLDB_DOCKER_PORT}"
    volumes:
      - db_data:/var/lib/mysql
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-p${MYSQLDB_ROOT_PASSWORD}",
        ]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    depends_on:
      mysqldb:
        condition: service_healthy
    env_file: ./.env.docker
    environment:
      PORT: ${NODE_DOCKER_PORT}
      DB_HOST: mysqldb
      DB_USER: ${MYSQLDB_USER}
      DB_PASSWORD: ${MYSQLDB_ROOT_PASSWORD}
      DB_NAME: ${MYSQLDB_DATABASE}
      DB_PORT: ${MYSQLDB_DOCKER_PORT}
    ports:
      - "${NODE_LOCAL_PORT}:${NODE_DOCKER_PORT}"
    volumes:
      - ./.env.docker:/app/.env.docker

volumes:
  db_data:
